export const headerTable = [
  'Contractor',
  'client',
  'Month',
  ' total hours',
  'P/Hour',
  'total payment',
]
export const months = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
]

export const clients = ['Multilaser', 'Big', 'Apple', 'Amazon', 'Google']
export const contractors = ['John', 'Paul', 'George', 'Ringo']
export const INITIAL_STATE_31_DAYS_OBJ = {
  '1': 0,
  '2': 0,
  '3': 0,
  '4': 0,
  '5': 0,
  '6': 0,
  '7': 0,
  '8': 0,
  '9': 0,
  '10': 0,
  '11': 0,
  '12': 0,
  '13': 0,
  '14': 0,
  '15': 0,
  '16': 0,
  '17': 0,
  '18': 0,
  '19': 0,
  '20': 0,
  '21': 0,
  '22': 0,
  '23': 0,
  '24': 0,
  '25': 0,
  '26': 0,
  '27': 0,
  '28': 0,
  '29': 0,
  '30': 0,
  '31': 0,
}

export const bodyTable = [
  {
    id: 1,
    contractor: 'bruno fay',
    month: 'January',
    client: 'amazon',
    hours: '10',
    pHour: '20',
    workedDays: INITIAL_STATE_31_DAYS_OBJ,
  },
  {
    id: 1,
    contractor: 'james brown',
    month: 'February',
    client: 'amazon',
    hours: '10',
    pHour: '20',
    workedDays: INITIAL_STATE_31_DAYS_OBJ,
  },
  {
    id: 1,
    contractor: 'angela borges ',
    month: 'January',
    client: 'amazon',
    hours: '10',
    pHour: '20',
    workedDays: INITIAL_STATE_31_DAYS_OBJ,
  },
  {
    id: 1,
    contractor: 'john doe ',
    month: 'January',
    client: 'amazon',
    hours: '10',
    pHour: '20',
    workedDays: INITIAL_STATE_31_DAYS_OBJ,
  },
  {
    id: 1,
    contractor: 'bruno fay',
    month: 'February',
    client: 'amazon',
    hours: '10',
    pHour: '20',
    workedDays: INITIAL_STATE_31_DAYS_OBJ,
  },
]
