export const headerTable = [
  'name',
  'client',
  'Month',
  ' total hours',
  'P/Hour',
  'total payment',
]
export const months = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
]
export const bodyTable = [
  {
    id: 1,
    name: 'bruno fay',
    month: 'January',
    client: 'amazon',
    hours: '10',
    pHour: '20',
  },
  {
    id: 1,
    name: 'james brown',
    month: 'January',
    client: 'amazon',
    hours: '10',
    pHour: '20',
  },
  {
    id: 1,
    name: 'angela borges ',
    month: 'January',
    client: 'amazon',
    hours: '10',
    pHour: '20',
  },
  {
    id: 1,
    name: 'bruno fay',
    month: 'February',
    client: 'amazon',
    hours: '10',
    pHour: '20',
  },
]
