export const headerTableClients = [
  'Status',
  'Name',
  'Working Days',
  'Working Hours',
]
export const headerTableContractor = [
  'Date',
  'Client',
  'Worked Hours',
  'P/Hour',
]
export const headerTableContractors = [
  'status',
  'fullname',
  'ITIN/SSN/EIN',
  'Phone',
  'address',
]
export const headerTableJobs = [
  'status',
  'Contractor',
  'client',
  'Month',
  ' total hours',
  'P/Hour',
  'Taxes',
  'Shirts',
  'Status Payment',
  'total payment',
]
export const headerTablePayments = [
  'Contractor',
  '1 - 15',
  'taxes',
  'Payment Type',
  'Payment Identifier',
  'quinzena 2',
  'taxes',
  'Payment Type',
  'Payment Identifier',
  'total taxes',
  'total shirts',
  'Total Month',
]

export const headerTableReports = [
  'month',
  'invoices',
  'labour payroll',
  'van/fuel & oil',
  'fuel & oil',
  'equipment',
  'uniform',
  'repairs & maintenance',
  'advertisement',
  'contractors workers',
  'global',
  'insurance & tax',
  'meals',
  'chemical & consumables',
  'office expenses',
  'extras',
  'general total monthly',
]

export const headerTableMonthsReports = [
  'id',
  'date',
  'payed for',
  'payment form',
  'payment identifier',
  'invoices',
  'labour Payroll',
  'van/fuel & oil',
  'fuel & oil',
  'equipment',
  'uniform',
  'repairs & maintenance',
  'advertisement',
  'contractor workers',
  'global',
  'insurance & tax',
  'meals',
  'chemical & consumables',
  'office expenses',
  'extras',
  'save',
]
