export const headerTable = ['Status', 'Name', 'Working Days', 'Working Hours']
export const bodyTable = [
  {
    id: 1,
    name: 'apple',
    status: 'Active',
    monday: false,
    tuesday: false,
    wednesday: false,
    thursday: true,
    friday: false,
    saturday: true,
    sunday: false,
    start: '08:00',
    end: '17:00',
  },
  {
    id: 11,
    name: 'Big',
    status: 'Active',
    monday: true,
    tuesday: true,
    wednesday: true,
    thursday: true,
    friday: true,
    saturday: true,
    sunday: true,
    start: '10:00',
    end: '17:00',
  },
  {
    id: 12,
    name: 'amazon',
    status: 'Active',
    monday: true,
    tuesday: true,
    wednesday: true,
    thursday: true,
    friday: false,
    saturday: false,
    sunday: false,
    start: '08:00',
    end: '17:00',
  },
  {
    id: 14,
    name: 'multilaser',
    status: 'Inactive',
    monday: true,
    tuesday: true,
    wednesday: true,
    thursday: false,
    friday: false,
    saturday: false,
    sunday: true,
    start: '08:00',
    end: '17:00',
  },
]

export type Weekdays = [
  'monday',
  'tuesday',
  'wednesday',
  'thursday',
  'friday',
  'saturday',
  'sunday',
]
export const WEEKDAYS: Weekdays = [
  'monday',
  'tuesday',
  'wednesday',
  'thursday',
  'friday',
  'saturday',
  'sunday',
]
