export const bodyTable = [
  {
    id: 1,
    name: 'apple',
    status: 'ACTIVE',
    monday: false,
    tuesday: false,
    wednesday: false,
    thursday: true,
    friday: false,
    saturday: true,
    sunday: false,
    start: '08:00',
    end: '17:00',
  },
  {
    id: 11,
    name: 'Big',
    status: 'ACTIVE',
    monday: true,
    tuesday: true,
    wednesday: true,
    thursday: true,
    friday: true,
    saturday: true,
    sunday: true,
    start: '10:00',
    end: '17:00',
  },
  {
    id: 12,
    name: 'amazon',
    status: 'ACTIVE',
    monday: true,
    tuesday: true,
    wednesday: true,
    thursday: true,
    friday: false,
    saturday: false,
    sunday: false,
    start: '08:00',
    end: '17:00',
  },
  {
    id: 14,
    name: 'multilaser',
    status: 'INACTIVE',
    monday: true,
    tuesday: true,
    wednesday: true,
    thursday: false,
    friday: false,
    saturday: false,
    sunday: true,
    start: '08:00',
    end: '17:00',
  },
]
